export const LOAD_CONVERSION_UNITS = 'LOAD_CONVERSION_UNITS';
export const LOAD_CONVERSION_CURRENCIES = 'LOAD_CONVERSION_CURRENCIES';
export const CHANGE_CONVERSION_UNIT = 'CHANGE_CONVERSION_UNIT';

export const UPDATE_CONVERSION_FROM = 'UPDATE_CONVERSION_FROM';
export const UPDATE_CONVERSION_TO = 'UPDATE_CONVERSION_TO';
export const UPDATE_CONVERSION_AMOUNT = 'UPDATE_CONVERSION_AMOUNT';
export const UPDATE_CONVERSION_RESULT = 'UPDATE_CONVERSION_RESULT';
